# module category rules
jobeet_category:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetCategory
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

# module job rules
jobeet_job:
  class: sfDoctrineRouteCollection
  options:
    model:                JobeetJob
    module:               job
    prefix_path:          /job
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: job, action: index }
