# module job rules
job:
  class:   sfDoctrineRouteCollection
  options:
    model: JobeetJob
    column: token
    object_actions: { publish: put, extend: put }
    prefix_path:    /:sf_culture/job
  requirements:
    token: \w+
    sf_culture: (?:es|en)

job_show_user:
  url:     /:sf_culture/job/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: JobeetJob
    type: object
    method_for_query: retrieveActiveJob
  param:   { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]
    sf_culture: (?:es|en)

job_search:
  url:   /:sf_culture/search
  param: { module: job, action: search }
  requirements:
    sf_culture: (?:es|en)

# module category rules
category:
  url:      /:sf_culture/category/:slug
  class:    sfDoctrineRoute
  param:    { module: category, action: show }
  options:  { model: JobeetCategory, type: object, method: doSelectForSlug }
  requirements:
    sf_culture: (?:es|en)

# module affiliate rules
affiliate:
  class:   sfDoctrineRouteCollection
  options:
    model: JobeetAffiliate
    actions: [new, create]
    object_actions: { wait: get }
    prefix_path:    /:sf_culture/affiliate
  requirements:
    sf_culture: (?:es|en)

# module api rules
api_jobs:
  url:     /api/:token/jobs.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: JobeetJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)

# module language rules
change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

localized_homepage:
  url:   /:sf_culture/
  param: { module: job, action: index }
  requirements:
    sf_culture: (?:es|en)
